added users documentation
hummingbird-me/api-docs pull request #35
Opened 2017-06-19 08:37 UTC by JasonLighthunter

2017-06-21 15:40 UTC, wopian requested changes

2017-06-21 15:40 UTC, wopian commented on blueprint/users/users.mson
> +    + tiny: `https://media.kitsu.io/users/cover_images/1/small.jpg`
❌ Missing cache busting (`?1414038335`) for the cover images

2017-06-22 15:11 UTC, robyncuppen commented on blueprint/users/users.mson
> +    + tiny: `https://media.kitsu.io/users/cover_images/1/small.jpg`
<img width="599" alt="screen shot 2017-06-22 at 17 09 12" src="https://user-images.githubusercontent.com/6705325/27441381-aa0e4a5e-576d-11e7-8a22-119c7cf82036.png">

This is what I got from the api. I don't miss anything

2017-06-22 15:25 UTC, wopian commented on blueprint/users/users.mson
> +    + tiny: `https://media.kitsu.io/users/cover_images/1/small.jpg`
Its gone again 😕

2017-06-22 15:27 UTC, wopian commented on blueprint/users/users.mson
> +            + related: `https://kitsu.io/api/edge/users/1/stats`
New relationship added

```json
"oneSignalPlayers": {
  "links": {
    "self": "https://kitsu.io/api/edge/users/1/relationships/one-signal-players",
    "related": "https://kitsu.io/api/edge/users/1/one-signal-players"
  }
}
```

2017-06-22 15:46 UTC, wopian approved these changes

2017-06-22 15:46 UTC, merged